-- Supabase SQL Editor 用
-- このアプリが利用するテーブルを、既存構成を崩さず PostgreSQL / Supabase に作成します。

CREATE TABLE IF NOT EXISTS todo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100)
);

INSERT INTO todo (title)
SELECT 'テストデータ'
WHERE NOT EXISTS (
    SELECT 1 FROM todo WHERE title = 'テストデータ'
);

CREATE TABLE IF NOT EXISTS product_master (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255),
    tax_price INTEGER
);

CREATE TABLE IF NOT EXISTS slip (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slip_no VARCHAR(20),
    staff_name VARCHAR(50),
    customer_name VARCHAR(100),
    contact_info VARCHAR(100),
    email_address VARCHAR(100),
    loan_date DATE,
    return_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS slip_detail (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slip_id INTEGER,
    code VARCHAR(20),
    name VARCHAR(100),
    price INTEGER,
    tax_price INTEGER,
    credit VARCHAR(100),
    media_name VARCHAR(100),
    release_date DATE,
    note VARCHAR(255),
    returned BOOLEAN DEFAULT FALSE,
    returned_date DATE,
    CONSTRAINT fk_slip_detail_slip
        FOREIGN KEY (slip_id) REFERENCES slip(id)
);

CREATE TABLE IF NOT EXISTS slip_media (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slip_id INTEGER,
    media_name VARCHAR(100),
    project_name VARCHAR(100),
    release_date DATE,
    note VARCHAR(255),
    CONSTRAINT fk_slip_media_slip
        FOREIGN KEY (slip_id) REFERENCES slip(id)
);

ALTER TABLE slip
ADD COLUMN IF NOT EXISTS customer_name VARCHAR(100);

ALTER TABLE slip
ADD COLUMN IF NOT EXISTS contact_info VARCHAR(100);

ALTER TABLE slip
ADD COLUMN IF NOT EXISTS email_address VARCHAR(100);

ALTER TABLE slip_media
ADD COLUMN IF NOT EXISTS project_name VARCHAR(100);

ALTER TABLE slip_detail
ADD COLUMN IF NOT EXISTS returned BOOLEAN DEFAULT FALSE;

ALTER TABLE slip_detail
ADD COLUMN IF NOT EXISTS returned_date DATE;

CREATE TABLE IF NOT EXISTS master_setting (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_text VARCHAR(1000),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO master_setting (master_text)
SELECT 'ここにExcelに表示する固定文言を入力してください'
WHERE NOT EXISTS (
    SELECT 1 FROM master_setting
);
