ALTER TABLE slip
ADD COLUMN IF NOT EXISTS customer_name VARCHAR(100);

ALTER TABLE slip
ADD COLUMN IF NOT EXISTS contact_info VARCHAR(100);

ALTER TABLE slip
ADD COLUMN IF NOT EXISTS email_address VARCHAR(100);
