server.port=${PORT:10000}
spring.application.name=demo
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
app.database.platform=${APP_DATABASE_PLATFORM:mysql}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sampledb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:machochanful}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
spring.datasource.hikari.initialization-fail-timeout=${SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT:0}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.sql.init.encoding=UTF-8
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.example.demo.entity
google.sheets.spreadsheet-id=${GOOGLE_SHEETS_SPREADSHEET_ID:1VIK0TdvVH7-7zc_VJmdvc7qlcMEqki5aj8UoUamHO7Y}
google.sheets.range=${GOOGLE_SHEETS_RANGE:0619newarrival!A:I}
google.sheets.credentials-location=${GOOGLE_SHEETS_CREDENTIALS_LOCATION:classpath:credentials.json}
